name: deploy_main_aws
on:
  push:
    branches: ["main"]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
        
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: lpnearx 
        tags: latest
        registry: ghcr.io/manoelgomesdev
        dockerfile: Dockerfile
        username: manoelgomesdev
        password: ${{ secrets.GH_TOKEN }} 

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.AWS_TOKEN }}
        script: |
          cd /etc/nearx
          cat .docker-pass/manoel | sudo docker login ghcr.io --username manoelgomesdev --password-stdin
          cd compose
          sudo docker compose pull lpnearx
          sudo docker compose up -d lpnearx
